### ISSUE TITLE
Populated planets are ALWAYS my starter planet, and there is no mine.

### ISSUE THREAD

**Issue by JohnyLongShoes** [Cyberjolteon/Citybound#2]
Now this sucks, every planet I've made a new character on has been a populated planet, which might be my bad luck, but still, the problem is there is no mine, which means I cant get the 20 crystals unless I mine ALL THE WAY down to near the core and get some, which is a hassle and annoying.

Could you please fix this?

**Comment by Cyberjolteon** [comment]
Hi JohnyLongShoes,

@GhengopelALPHA implemented a fix for this issue, this will be live in the next patch.
we will release this patch very soon

**Comment by Cyberjolteon** [comment]
Resolved by the latest patch
